/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookDto { 
    authorId?: string;
    genreId?: string;
    id?: string;
    name?: string;
    price?: number;
    publicationDate?: number;
    publishingOffice?: string;
}

